services:
  db:
    container_name: database
    image: postgres:16.1
    restart: always
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
    volumes:
      - ./pgdata:/var/lib/postgresql/mydata
    ports:
      - ${DATABASE_PORT}:5432

  server:
    container_name: server
    build:
      context: '.'
      dockerfile: Dockerfile.dev
    restart: always
    environment:
      - SERVER_PORT=3000
    ports:
      - ${SERVER_PORT}:3000
    depends_on:
      - 'db'
    volumes:
      - .:/app
      - /app/node_modules
