import { Country } from '#database/entities/countries.entity';

export const countries: Country[] = [
  {
    id: 1,
    iso: 'AF',
    name: 'Afghanistan',
    upperName: 'AFGHANISTAN',
    iso3: 'AFG',
    numCode: 4,
    phoneCode: 93,
  },
  {
    id: 2,
    iso: 'AL',
    name: 'Albania',
    upperName: 'ALBANIA',
    iso3: 'ALB',
    numCode: 8,
    phoneCode: 355,
  },
  {
    id: 3,
    iso: 'DZ',
    name: 'Algeria',
    upperName: 'ALGERIA',
    iso3: 'DZA',
    numCode: 12,
    phoneCode: 213,
  },
  {
    id: 4,
    iso: 'AS',
    name: 'American Samoa',
    upperName: 'AMERICAN SAMOA',
    iso3: 'ASM',
    numCode: 16,
    phoneCode: 1684,
  },
  {
    id: 5,
    iso: 'AD',
    name: 'Andorra',
    upperName: 'ANDORRA',
    iso3: 'AND',
    numCode: 20,
    phoneCode: 376,
  },
  {
    id: 6,
    iso: 'AO',
    name: 'Angola',
    upperName: 'ANGOLA',
    iso3: 'AGO',
    numCode: 24,
    phoneCode: 244,
  },
  {
    id: 7,
    iso: 'AI',
    name: 'Anguilla',
    upperName: 'ANGUILLA',
    iso3: 'AIA',
    numCode: 660,
    phoneCode: 1264,
  },
  {
    id: 8,
    iso: 'AQ',
    name: 'Antarctica',
    upperName: 'ANTARCTICA',
    iso3: 'ATA',
    numCode: 10,
    phoneCode: 0,
  },
  {
    id: 9,
    iso: 'AG',
    name: 'Antigua and Barbuda',
    upperName: 'ANTIGUA AND BARBUDA',
    iso3: 'ATG',
    numCode: 28,
    phoneCode: 1268,
  },
  {
    id: 10,
    iso: 'AR',
    name: 'Argentina',
    upperName: 'ARGENTINA',
    iso3: 'ARG',
    numCode: 32,
    phoneCode: 54,
  },
  {
    id: 11,
    iso: 'AM',
    name: 'Armenia',
    upperName: 'ARMENIA',
    iso3: 'ARM',
    numCode: 51,
    phoneCode: 374,
  },
  {
    id: 12,
    iso: 'AW',
    name: 'Aruba',
    upperName: 'ARUBA',
    iso3: 'ABW',
    numCode: 533,
    phoneCode: 297,
  },
  {
    id: 13,
    iso: 'AU',
    name: 'Australia',
    upperName: 'AUSTRALIA',
    iso3: 'AUS',
    numCode: 36,
    phoneCode: 61,
  },
  {
    id: 14,
    iso: 'AT',
    name: 'Austria',
    upperName: 'AUSTRIA',
    iso3: 'AUT',
    numCode: 40,
    phoneCode: 43,
  },
  {
    id: 15,
    iso: 'AZ',
    name: 'Azerbaijan',
    upperName: 'AZERBAIJAN',
    iso3: 'AZE',
    numCode: 31,
    phoneCode: 994,
  },
  {
    id: 16,
    iso: 'BS',
    name: 'Bahamas',
    upperName: 'BAHAMAS',
    iso3: 'BHS',
    numCode: 44,
    phoneCode: 1242,
  },
  {
    id: 17,
    iso: 'BH',
    name: 'Bahrain',
    upperName: 'BAHRAIN',
    iso3: 'BHR',
    numCode: 48,
    phoneCode: 973,
  },
  {
    id: 18,
    iso: 'BD',
    name: 'Bangladesh',
    upperName: 'BANGLADESH',
    iso3: 'BGD',
    numCode: 50,
    phoneCode: 880,
  },
  {
    id: 19,
    iso: 'BB',
    name: 'Barbados',
    upperName: 'BARBADOS',
    iso3: 'BRB',
    numCode: 52,
    phoneCode: 1246,
  },
  {
    id: 20,
    iso: 'BY',
    name: 'Belarus',
    upperName: 'BELARUS',
    iso3: 'BLR',
    numCode: 112,
    phoneCode: 375,
  },
  {
    id: 21,
    iso: 'BE',
    name: 'Belgium',
    upperName: 'BELGIUM',
    iso3: 'BEL',
    numCode: 56,
    phoneCode: 32,
  },
  {
    id: 22,
    iso: 'BZ',
    name: 'Belize',
    upperName: 'BELIZE',
    iso3: 'BLZ',
    numCode: 84,
    phoneCode: 501,
  },
  {
    id: 23,
    iso: 'BJ',
    name: 'Benin',
    upperName: 'BENIN',
    iso3: 'BEN',
    numCode: 204,
    phoneCode: 229,
  },
  {
    id: 24,
    iso: 'BM',
    name: 'Bermuda',
    upperName: 'BERMUDA',
    iso3: 'BMU',
    numCode: 60,
    phoneCode: 1441,
  },
  {
    id: 25,
    iso: 'BT',
    name: 'Bhutan',
    upperName: 'BHUTAN',
    iso3: 'BTN',
    numCode: 64,
    phoneCode: 975,
  },
  {
    id: 26,
    iso: 'BO',
    name: 'Bolivia',
    upperName: 'BOLIVIA',
    iso3: 'BOL',
    numCode: 68,
    phoneCode: 591,
  },
  {
    id: 27,
    iso: 'BA',
    name: 'Bosnia and Herzegovina',
    upperName: 'BOSNIA AND HERZEGOVINA',
    iso3: 'BIH',
    numCode: 70,
    phoneCode: 387,
  },
  {
    id: 28,
    iso: 'BW',
    name: 'Botswana',
    upperName: 'BOTSWANA',
    iso3: 'BWA',
    numCode: 72,
    phoneCode: 267,
  },
  {
    id: 29,
    iso: 'BV',
    name: 'Bouvet Island',
    upperName: 'BOUVET ISLAND',
    iso3: 'BVT',
    numCode: 74,
    phoneCode: 0,
  },
  {
    id: 30,
    iso: 'BR',
    name: 'Brazil',
    upperName: 'BRAZIL',
    iso3: 'BRA',
    numCode: 76,
    phoneCode: 55,
  },
  {
    id: 31,
    iso: 'IO',
    name: 'British Indian Ocean Territory',
    upperName: 'BRITISH INDIAN OCEAN TERRITORY',
    iso3: 'IOT',
    numCode: 86,
    phoneCode: 246,
  },
  {
    id: 32,
    iso: 'BN',
    name: 'Brunei Darussalam',
    upperName: 'BRUNEI DARUSSALAM',
    iso3: 'BRN',
    numCode: 96,
    phoneCode: 673,
  },
  {
    id: 33,
    iso: 'BG',
    name: 'Bulgaria',
    upperName: 'BULGARIA',
    iso3: 'BGR',
    numCode: 100,
    phoneCode: 359,
  },
  {
    id: 34,
    iso: 'BF',
    name: 'Burkina Faso',
    upperName: 'BURKINA FASO',
    iso3: 'BFA',
    numCode: 854,
    phoneCode: 226,
  },
  {
    id: 35,
    iso: 'BI',
    name: 'Burundi',
    upperName: 'BURUNDI',
    iso3: 'BDI',
    numCode: 108,
    phoneCode: 257,
  },
  {
    id: 36,
    iso: 'KH',
    name: 'Cambodia',
    upperName: 'CAMBODIA',
    iso3: 'KHM',
    numCode: 116,
    phoneCode: 855,
  },
  {
    id: 37,
    iso: 'CM',
    name: 'Cameroon',
    upperName: 'CAMEROON',
    iso3: 'CMR',
    numCode: 120,
    phoneCode: 237,
  },
  {
    id: 38,
    iso: 'CA',
    name: 'Canada',
    upperName: 'CANADA',
    iso3: 'CAN',
    numCode: 124,
    phoneCode: 1,
  },
  {
    id: 39,
    iso: 'CV',
    name: 'Cape Verde',
    upperName: 'CAPE VERDE',
    iso3: 'CPV',
    numCode: 132,
    phoneCode: 238,
  },
  {
    id: 40,
    iso: 'KY',
    name: 'Cayman Islands',
    upperName: 'CAYMAN ISLANDS',
    iso3: 'CYM',
    numCode: 136,
    phoneCode: 1345,
  },
  {
    id: 41,
    iso: 'CF',
    name: 'Central African Republic',
    upperName: 'CENTRAL AFRICAN REPUBLIC',
    iso3: 'CAF',
    numCode: 140,
    phoneCode: 236,
  },
  {
    id: 42,
    iso: 'TD',
    name: 'Chad',
    upperName: 'CHAD',
    iso3: 'TCD',
    numCode: 148,
    phoneCode: 235,
  },
  {
    id: 43,
    iso: 'CL',
    name: 'Chile',
    upperName: 'CHILE',
    iso3: 'CHL',
    numCode: 152,
    phoneCode: 56,
  },
  {
    id: 44,
    iso: 'CN',
    name: 'China',
    upperName: 'CHINA',
    iso3: 'CHN',
    numCode: 156,
    phoneCode: 86,
  },
  {
    id: 45,
    iso: 'CX',
    name: 'Christmas Island',
    upperName: 'CHRISTMAS ISLAND',
    iso3: 'CXR',
    numCode: 162,
    phoneCode: 61,
  },
  {
    id: 46,
    iso: 'CC',
    name: 'Cocos (Keeling) Islands',
    upperName: 'COCOS (KEELING) ISLANDS',
    iso3: null,
    numCode: null,
    phoneCode: 672,
  },
  {
    id: 47,
    iso: 'CO',
    name: 'Colombia',
    upperName: 'COLOMBIA',
    iso3: 'COL',
    numCode: 170,
    phoneCode: 57,
  },
  {
    id: 48,
    iso: 'KM',
    name: 'Comoros',
    upperName: 'COMOROS',
    iso3: 'COM',
    numCode: 174,
    phoneCode: 269,
  },
  {
    id: 49,
    iso: 'CG',
    name: 'Congo',
    upperName: 'CONGO',
    iso3: 'COG',
    numCode: 178,
    phoneCode: 242,
  },
  {
    id: 50,
    iso: 'CD',
    name: 'Congo, the Democratic Republic of the',
    upperName: 'CONGO, THE DEMOCRATIC REPUBLIC OF THE',
    iso3: 'COD',
    numCode: 180,
    phoneCode: 242,
  },
  {
    id: 51,
    iso: 'CK',
    name: 'Cook Islands',
    upperName: 'COOK ISLANDS',
    iso3: 'COK',
    numCode: 184,
    phoneCode: 682,
  },
  {
    id: 52,
    iso: 'CR',
    name: 'Costa Rica',
    upperName: 'COSTA RICA',
    iso3: 'CRI',
    numCode: 188,
    phoneCode: 506,
  },
  {
    id: 53,
    iso: 'CI',
    name: "Cote D'Ivoire",
    upperName: "COTE D'IVOIRE",
    iso3: 'CIV',
    numCode: 384,
    phoneCode: 225,
  },
  {
    id: 54,
    iso: 'HR',
    name: 'Croatia',
    upperName: 'CROATIA',
    iso3: 'HRV',
    numCode: 191,
    phoneCode: 385,
  },
  {
    id: 55,
    iso: 'CU',
    name: 'Cuba',
    upperName: 'CUBA',
    iso3: 'CUB',
    numCode: 192,
    phoneCode: 53,
  },
  {
    id: 56,
    iso: 'CY',
    name: 'Cyprus',
    upperName: 'CYPRUS',
    iso3: 'CYP',
    numCode: 196,
    phoneCode: 357,
  },
  {
    id: 57,
    iso: 'CZ',
    name: 'Czech Republic',
    upperName: 'CZECHIA',
    iso3: 'CZE',
    numCode: 203,
    phoneCode: 420,
  },
  {
    id: 58,
    iso: 'DK',
    name: 'Denmark',
    upperName: 'DENMARK',
    iso3: 'DNK',
    numCode: 208,
    phoneCode: 45,
  },
  {
    id: 59,
    iso: 'DJ',
    name: 'Djibouti',
    upperName: 'DJIBOUTI',
    iso3: 'DJI',
    numCode: 262,
    phoneCode: 253,
  },
  {
    id: 60,
    iso: 'DM',
    name: 'Dominica',
    upperName: 'DOMINICA',
    iso3: 'DMA',
    numCode: 212,
    phoneCode: 1767,
  },
  {
    id: 61,
    iso: 'DO',
    name: 'Dominican Republic',
    upperName: 'DOMINICAN REPUBLIC',
    iso3: 'DOM',
    numCode: 214,
    phoneCode: 1,
  },
  {
    id: 62,
    iso: 'EC',
    name: 'Ecuador',
    upperName: 'ECUADOR',
    iso3: 'ECU',
    numCode: 218,
    phoneCode: 593,
  },
  {
    id: 63,
    iso: 'EG',
    name: 'Egypt',
    upperName: 'EGYPT',
    iso3: 'EGY',
    numCode: 818,
    phoneCode: 20,
  },
  {
    id: 64,
    iso: 'SV',
    name: 'El Salvador',
    upperName: 'EL SALVADOR',
    iso3: 'SLV',
    numCode: 222,
    phoneCode: 503,
  },
  {
    id: 65,
    iso: 'GQ',
    name: 'Equatorial Guinea',
    upperName: 'EQUATORIAL GUINEA',
    iso3: 'GNQ',
    numCode: 226,
    phoneCode: 240,
  },
  {
    id: 66,
    iso: 'ER',
    name: 'Eritrea',
    upperName: 'ERITREA',
    iso3: 'ERI',
    numCode: 232,
    phoneCode: 291,
  },
  {
    id: 67,
    iso: 'EE',
    name: 'Estonia',
    upperName: 'ESTONIA',
    iso3: 'EST',
    numCode: 233,
    phoneCode: 372,
  },
  {
    id: 68,
    iso: 'ET',
    name: 'Ethiopia',
    upperName: 'ETHIOPIA',
    iso3: 'ETH',
    numCode: 231,
    phoneCode: 251,
  },
  {
    id: 69,
    iso: 'FK',
    name: 'Falkland Islands (Malvinas)',
    upperName: 'FALKLAND ISLANDS (MALVINAS)',
    iso3: 'FLK',
    numCode: 238,
    phoneCode: 500,
  },
  {
    id: 70,
    iso: 'FO',
    name: 'Faroe Islands',
    upperName: 'FAROE ISLANDS',
    iso3: 'FRO',
    numCode: 234,
    phoneCode: 298,
  },
  {
    id: 71,
    iso: 'FJ',
    name: 'Fiji',
    upperName: 'FIJI',
    iso3: 'FJI',
    numCode: 242,
    phoneCode: 679,
  },
  {
    id: 72,
    iso: 'FI',
    name: 'Finland',
    upperName: 'FINLAND',
    iso3: 'FIN',
    numCode: 246,
    phoneCode: 358,
  },
  {
    id: 73,
    iso: 'FR',
    name: 'France',
    upperName: 'FRANCE',
    iso3: 'FRA',
    numCode: 250,
    phoneCode: 33,
  },
  {
    id: 74,
    iso: 'GF',
    name: 'French Guiana',
    upperName: 'FRENCH GUIANA',
    iso3: 'GUF',
    numCode: 254,
    phoneCode: 594,
  },
  {
    id: 75,
    iso: 'PF',
    name: 'French Polynesia',
    upperName: 'FRENCH POLYNESIA',
    iso3: 'PYF',
    numCode: 258,
    phoneCode: 689,
  },
  {
    id: 76,
    iso: 'TF',
    name: 'French Southern Territories',
    upperName: 'FRENCH SOUTHERN TERRITORIES',
    iso3: 'ATF',
    numCode: 260,
    phoneCode: 0,
  },
  {
    id: 77,
    iso: 'GA',
    name: 'Gabon',
    upperName: 'GABON',
    iso3: 'GAB',
    numCode: 266,
    phoneCode: 241,
  },
  {
    id: 78,
    iso: 'GM',
    name: 'Gambia',
    upperName: 'GAMBIA',
    iso3: 'GMB',
    numCode: 270,
    phoneCode: 220,
  },
  {
    id: 79,
    iso: 'GE',
    name: 'Georgia',
    upperName: 'GEORGIA',
    iso3: 'GEO',
    numCode: 268,
    phoneCode: 995,
  },
  {
    id: 80,
    iso: 'DE',
    name: 'Germany',
    upperName: 'GERMANY',
    iso3: 'DEU',
    numCode: 276,
    phoneCode: 49,
  },
  {
    id: 81,
    iso: 'GH',
    name: 'Ghana',
    upperName: 'GHANA',
    iso3: 'GHA',
    numCode: 288,
    phoneCode: 233,
  },
  {
    id: 82,
    iso: 'GI',
    name: 'Gibraltar',
    upperName: 'GIBRALTAR',
    iso3: 'GIB',
    numCode: 292,
    phoneCode: 350,
  },
  {
    id: 83,
    iso: 'GR',
    name: 'Greece',
    upperName: 'GREECE',
    iso3: 'GRC',
    numCode: 300,
    phoneCode: 30,
  },
  {
    id: 84,
    iso: 'GL',
    name: 'Greenland',
    upperName: 'GREENLAND',
    iso3: 'GRL',
    numCode: 304,
    phoneCode: 299,
  },
  {
    id: 85,
    iso: 'GD',
    name: 'Grenada',
    upperName: 'GRENADA',
    iso3: 'GRD',
    numCode: 308,
    phoneCode: 1473,
  },
  {
    id: 86,
    iso: 'GP',
    name: 'Guadeloupe',
    upperName: 'GUADELOUPE',
    iso3: 'GLP',
    numCode: 312,
    phoneCode: 590,
  },
  {
    id: 87,
    iso: 'GU',
    name: 'Guam',
    upperName: 'GUAM',
    iso3: 'GUM',
    numCode: 316,
    phoneCode: 1671,
  },
  {
    id: 88,
    iso: 'GT',
    name: 'Guatemala',
    upperName: 'GUATEMALA',
    iso3: 'GTM',
    numCode: 320,
    phoneCode: 502,
  },
  {
    id: 89,
    iso: 'GN',
    name: 'Guinea',
    upperName: 'GUINEA',
    iso3: 'GIN',
    numCode: 324,
    phoneCode: 224,
  },
  {
    id: 90,
    iso: 'GW',
    name: 'Guinea-Bissau',
    upperName: 'GUINEA-BISSAU',
    iso3: 'GNB',
    numCode: 624,
    phoneCode: 245,
  },
  {
    id: 91,
    iso: 'GY',
    name: 'Guyana',
    upperName: 'GUYANA',
    iso3: 'GUY',
    numCode: 328,
    phoneCode: 592,
  },
  {
    id: 92,
    iso: 'HT',
    name: 'Haiti',
    upperName: 'HAITI',
    iso3: 'HTI',
    numCode: 332,
    phoneCode: 509,
  },
  {
    id: 93,
    iso: 'HM',
    name: 'Heard Island and Mcdonald Islands',
    upperName: 'HEARD ISLAND AND MCDONALD ISLANDS',
    iso3: 'HMD',
    numCode: 334,
    phoneCode: 0,
  },
  {
    id: 94,
    iso: 'VA',
    name: 'Holy See (Vatican City State)',
    upperName: 'HOLY SEE (VATICAN CITY STATE)',
    iso3: 'VAT',
    numCode: 336,
    phoneCode: 39,
  },
  {
    id: 95,
    iso: 'HN',
    name: 'Honduras',
    upperName: 'HONDURAS',
    iso3: 'HND',
    numCode: 340,
    phoneCode: 504,
  },
  {
    id: 96,
    iso: 'HK',
    name: 'Hong Kong',
    upperName: 'HONG KONG',
    iso3: 'HKG',
    numCode: 344,
    phoneCode: 852,
  },
  {
    id: 97,
    iso: 'HU',
    name: 'Hungary',
    upperName: 'HUNGARY',
    iso3: 'HUN',
    numCode: 348,
    phoneCode: 36,
  },
  {
    id: 98,
    iso: 'IS',
    name: 'Iceland',
    upperName: 'ICELAND',
    iso3: 'ISL',
    numCode: 352,
    phoneCode: 354,
  },
  {
    id: 99,
    iso: 'IN',
    name: 'India',
    upperName: 'INDIA',
    iso3: 'IND',
    numCode: 356,
    phoneCode: 91,
  },
  {
    id: 100,
    iso: 'ID',
    name: 'Indonesia',
    upperName: 'INDONESIA',
    iso3: 'IDN',
    numCode: 360,
    phoneCode: 62,
  },
  {
    id: 101,
    iso: 'IR',
    name: 'Iran, Islamic Republic of',
    upperName: 'IRAN, ISLAMIC REPUBLIC OF',
    iso3: 'IRN',
    numCode: 364,
    phoneCode: 98,
  },
  {
    id: 102,
    iso: 'IQ',
    name: 'Iraq',
    upperName: 'IRAQ',
    iso3: 'IRQ',
    numCode: 368,
    phoneCode: 964,
  },
  {
    id: 103,
    iso: 'IE',
    name: 'Ireland',
    upperName: 'IRELAND',
    iso3: 'IRL',
    numCode: 372,
    phoneCode: 353,
  },
  {
    id: 104,
    iso: 'IL',
    name: 'Israel',
    upperName: 'ISRAEL',
    iso3: 'ISR',
    numCode: 376,
    phoneCode: 972,
  },
  {
    id: 105,
    iso: 'IT',
    name: 'Italy',
    upperName: 'ITALY',
    iso3: 'ITA',
    numCode: 380,
    phoneCode: 39,
  },
  {
    id: 106,
    iso: 'JM',
    name: 'Jamaica',
    upperName: 'JAMAICA',
    iso3: 'JAM',
    numCode: 388,
    phoneCode: 1876,
  },
  {
    id: 107,
    iso: 'JP',
    name: 'Japan',
    upperName: 'JAPAN',
    iso3: 'JPN',
    numCode: 392,
    phoneCode: 81,
  },
  {
    id: 108,
    iso: 'JO',
    name: 'Jordan',
    upperName: 'JORDAN',
    iso3: 'JOR',
    numCode: 400,
    phoneCode: 962,
  },
  {
    id: 109,
    iso: 'KZ',
    name: 'Kazakhstan',
    upperName: 'KAZAKHSTAN',
    iso3: 'KAZ',
    numCode: 398,
    phoneCode: 7,
  },
  {
    id: 110,
    iso: 'KE',
    name: 'Kenya',
    upperName: 'KENYA',
    iso3: 'KEN',
    numCode: 404,
    phoneCode: 254,
  },
  {
    id: 111,
    iso: 'KI',
    name: 'Kiribati',
    upperName: 'KIRIBATI',
    iso3: 'KIR',
    numCode: 296,
    phoneCode: 686,
  },
  {
    id: 112,
    iso: 'KP',
    name: "Korea, Democratic People's Republic of",
    upperName: "KOREA, DEMOCRATIC PEOPLE'S REPUBLIC OF",
    iso3: 'PRK',
    numCode: 408,
    phoneCode: 850,
  },
  {
    id: 113,
    iso: 'KR',
    name: 'Korea, Republic of',
    upperName: 'KOREA, REPUBLIC OF',
    iso3: 'KOR',
    numCode: 410,
    phoneCode: 82,
  },
  {
    id: 114,
    iso: 'KW',
    name: 'Kuwait',
    upperName: 'KUWAIT',
    iso3: 'KWT',
    numCode: 414,
    phoneCode: 965,
  },
  {
    id: 115,
    iso: 'KG',
    name: 'Kyrgyzstan',
    upperName: 'KYRGYZSTAN',
    iso3: 'KGZ',
    numCode: 417,
    phoneCode: 996,
  },
  {
    id: 116,
    iso: 'LA',
    name: "Lao People's Democratic Republic",
    upperName: "LAO PEOPLE'S DEMOCRATIC REPUBLIC",
    iso3: 'LAO',
    numCode: 418,
    phoneCode: 856,
  },
  {
    id: 117,
    iso: 'LV',
    name: 'Latvia',
    upperName: 'LATVIA',
    iso3: 'LVA',
    numCode: 428,
    phoneCode: 371,
  },
  {
    id: 118,
    iso: 'LB',
    name: 'Lebanon',
    upperName: 'LEBANON',
    iso3: 'LBN',
    numCode: 422,
    phoneCode: 961,
  },
  {
    id: 119,
    iso: 'LS',
    name: 'Lesotho',
    upperName: 'LESOTHO',
    iso3: 'LSO',
    numCode: 426,
    phoneCode: 266,
  },
  {
    id: 120,
    iso: 'LR',
    name: 'Liberia',
    upperName: 'LIBERIA',
    iso3: 'LBR',
    numCode: 430,
    phoneCode: 231,
  },
  {
    id: 121,
    iso: 'LY',
    name: 'Libyan Arab Jamahiriya',
    upperName: 'LIBYAN ARAB JAMAHIRIYA',
    iso3: 'LBY',
    numCode: 434,
    phoneCode: 218,
  },
  {
    id: 122,
    iso: 'LI',
    name: 'Liechtenstein',
    upperName: 'LIECHTENSTEIN',
    iso3: 'LIE',
    numCode: 438,
    phoneCode: 423,
  },
  {
    id: 123,
    iso: 'LT',
    name: 'Lithuania',
    upperName: 'LITHUANIA',
    iso3: 'LTU',
    numCode: 440,
    phoneCode: 370,
  },
  {
    id: 124,
    iso: 'LU',
    name: 'Luxembourg',
    upperName: 'LUXEMBOURG',
    iso3: 'LUX',
    numCode: 442,
    phoneCode: 352,
  },
  {
    id: 125,
    iso: 'MO',
    name: 'Macao',
    upperName: 'MACAO',
    iso3: 'MAC',
    numCode: 446,
    phoneCode: 853,
  },
  {
    id: 126,
    iso: 'MK',
    name: 'North Macedonia',
    upperName: 'NORTH MACEDONIA',
    iso3: 'MKD',
    numCode: 807,
    phoneCode: 389,
  },
  {
    id: 127,
    iso: 'MG',
    name: 'Madagascar',
    upperName: 'MADAGASCAR',
    iso3: 'MDG',
    numCode: 450,
    phoneCode: 261,
  },
  {
    id: 128,
    iso: 'MW',
    name: 'Malawi',
    upperName: 'MALAWI',
    iso3: 'MWI',
    numCode: 454,
    phoneCode: 265,
  },
  {
    id: 129,
    iso: 'MY',
    name: 'Malaysia',
    upperName: 'MALAYSIA',
    iso3: 'MYS',
    numCode: 458,
    phoneCode: 60,
  },
  {
    id: 130,
    iso: 'MV',
    name: 'Maldives',
    upperName: 'MALDIVES',
    iso3: 'MDV',
    numCode: 462,
    phoneCode: 960,
  },
  {
    id: 131,
    iso: 'ML',
    name: 'Mali',
    upperName: 'MALI',
    iso3: 'MLI',
    numCode: 466,
    phoneCode: 223,
  },
  {
    id: 132,
    iso: 'MT',
    name: 'Malta',
    upperName: 'MALTA',
    iso3: 'MLT',
    numCode: 470,
    phoneCode: 356,
  },
  {
    id: 133,
    iso: 'MH',
    name: 'Marshall Islands',
    upperName: 'MARSHALL ISLANDS',
    iso3: 'MHL',
    numCode: 584,
    phoneCode: 692,
  },
  {
    id: 134,
    iso: 'MQ',
    name: 'Martinique',
    upperName: 'MARTINIQUE',
    iso3: 'MTQ',
    numCode: 474,
    phoneCode: 596,
  },
  {
    id: 135,
    iso: 'MR',
    name: 'Mauritania',
    upperName: 'MAURITANIA',
    iso3: 'MRT',
    numCode: 478,
    phoneCode: 222,
  },
  {
    id: 136,
    iso: 'MU',
    name: 'Mauritius',
    upperName: 'MAURITIUS',
    iso3: 'MUS',
    numCode: 480,
    phoneCode: 230,
  },
  {
    id: 137,
    iso: 'YT',
    name: 'Mayotte',
    upperName: 'MAYOTTE',
    iso3: 'MYT',
    numCode: 175,
    phoneCode: 269,
  },
  {
    id: 138,
    iso: 'MX',
    name: 'Mexico',
    upperName: 'MEXICO',
    iso3: 'MEX',
    numCode: 484,
    phoneCode: 52,
  },
  {
    id: 139,
    iso: 'FM',
    name: 'Micronesia, Federated States of',
    upperName: 'MICRONESIA, FEDERATED STATES OF',
    iso3: 'FSM',
    numCode: 583,
    phoneCode: 691,
  },
  {
    id: 140,
    iso: 'MD',
    name: 'Moldova, Republic of',
    upperName: 'MOLDOVA, REPUBLIC OF',
    iso3: 'MDA',
    numCode: 498,
    phoneCode: 373,
  },
  {
    id: 141,
    iso: 'MC',
    name: 'Monaco',
    upperName: 'MONACO',
    iso3: 'MCO',
    numCode: 492,
    phoneCode: 377,
  },
  {
    id: 142,
    iso: 'MN',
    name: 'Mongolia',
    upperName: 'MONGOLIA',
    iso3: 'MNG',
    numCode: 496,
    phoneCode: 976,
  },
  {
    id: 143,
    iso: 'MS',
    name: 'Montserrat',
    upperName: 'MONTSERRAT',
    iso3: 'MSR',
    numCode: 500,
    phoneCode: 1664,
  },
  {
    id: 144,
    iso: 'MA',
    name: 'Morocco',
    upperName: 'MOROCCO',
    iso3: 'MAR',
    numCode: 504,
    phoneCode: 212,
  },
  {
    id: 145,
    iso: 'MZ',
    name: 'Mozambique',
    upperName: 'MOZAMBIQUE',
    iso3: 'MOZ',
    numCode: 508,
    phoneCode: 258,
  },
  {
    id: 146,
    iso: 'MM',
    name: 'Myanmar',
    upperName: 'MYANMAR',
    iso3: 'MMR',
    numCode: 104,
    phoneCode: 95,
  },
  {
    id: 147,
    iso: 'NA',
    name: 'Namibia',
    upperName: 'NAMIBIA',
    iso3: 'NAM',
    numCode: 516,
    phoneCode: 264,
  },
  {
    id: 148,
    iso: 'NR',
    name: 'Nauru',
    upperName: 'NAURU',
    iso3: 'NRU',
    numCode: 520,
    phoneCode: 674,
  },
  {
    id: 149,
    iso: 'NP',
    name: 'Nepal',
    upperName: 'NEPAL',
    iso3: 'NPL',
    numCode: 524,
    phoneCode: 977,
  },
  {
    id: 150,
    iso: 'NL',
    name: 'Netherlands',
    upperName: 'NETHERLANDS',
    iso3: 'NLD',
    numCode: 528,
    phoneCode: 31,
  },
  {
    id: 151,
    iso: 'AN',
    name: 'Netherlands Antilles',
    upperName: 'NETHERLANDS ANTILLES',
    iso3: 'ANT',
    numCode: 530,
    phoneCode: 599,
  },
  {
    id: 152,
    iso: 'NC',
    name: 'New Caledonia',
    upperName: 'NEW CALEDONIA',
    iso3: 'NCL',
    numCode: 540,
    phoneCode: 687,
  },
  {
    id: 153,
    iso: 'NZ',
    name: 'New Zealand',
    upperName: 'NEW ZEALAND',
    iso3: 'NZL',
    numCode: 554,
    phoneCode: 64,
  },
  {
    id: 154,
    iso: 'NI',
    name: 'Nicaragua',
    upperName: 'NICARAGUA',
    iso3: 'NIC',
    numCode: 558,
    phoneCode: 505,
  },
  {
    id: 155,
    iso: 'NE',
    name: 'Niger',
    upperName: 'NIGER',
    iso3: 'NER',
    numCode: 562,
    phoneCode: 227,
  },
  {
    id: 156,
    iso: 'NG',
    name: 'Nigeria',
    upperName: 'NIGERIA',
    iso3: 'NGA',
    numCode: 566,
    phoneCode: 234,
  },
  {
    id: 157,
    iso: 'NU',
    name: 'Niue',
    upperName: 'NIUE',
    iso3: 'NIU',
    numCode: 570,
    phoneCode: 683,
  },
  {
    id: 158,
    iso: 'NF',
    name: 'Norfolk Island',
    upperName: 'NORFOLK ISLAND',
    iso3: 'NFK',
    numCode: 574,
    phoneCode: 672,
  },
  {
    id: 159,
    iso: 'MP',
    name: 'Northern Mariana Islands',
    upperName: 'NORTHERN MARIANA ISLANDS',
    iso3: 'MNP',
    numCode: 580,
    phoneCode: 1670,
  },
  {
    id: 160,
    iso: 'NO',
    name: 'Norway',
    upperName: 'NORWAY',
    iso3: 'NOR',
    numCode: 578,
    phoneCode: 47,
  },
  {
    id: 161,
    iso: 'OM',
    name: 'Oman',
    upperName: 'OMAN',
    iso3: 'OMN',
    numCode: 512,
    phoneCode: 968,
  },
  {
    id: 162,
    iso: 'PK',
    name: 'Pakistan',
    upperName: 'PAKISTAN',
    iso3: 'PAK',
    numCode: 586,
    phoneCode: 92,
  },
  {
    id: 163,
    iso: 'PW',
    name: 'Palau',
    upperName: 'PALAU',
    iso3: 'PLW',
    numCode: 585,
    phoneCode: 680,
  },
  {
    id: 164,
    iso: 'PS',
    name: 'Palestinian Territory, Occupied',
    upperName: 'PALESTINIAN TERRITORY, OCCUPIED',
    iso3: null,
    numCode: null,
    phoneCode: 970,
  },
  {
    id: 165,
    iso: 'PA',
    name: 'Panama',
    upperName: 'PANAMA',
    iso3: 'PAN',
    numCode: 591,
    phoneCode: 507,
  },
  {
    id: 166,
    iso: 'PG',
    name: 'Papua New Guinea',
    upperName: 'PAPUA NEW GUINEA',
    iso3: 'PNG',
    numCode: 598,
    phoneCode: 675,
  },
  {
    id: 167,
    iso: 'PY',
    name: 'Paraguay',
    upperName: 'PARAGUAY',
    iso3: 'PRY',
    numCode: 600,
    phoneCode: 595,
  },
  {
    id: 168,
    iso: 'PE',
    name: 'Peru',
    upperName: 'PERU',
    iso3: 'PER',
    numCode: 604,
    phoneCode: 51,
  },
  {
    id: 169,
    iso: 'PH',
    name: 'Philippines',
    upperName: 'PHILIPPINES',
    iso3: 'PHL',
    numCode: 608,
    phoneCode: 63,
  },
  {
    id: 170,
    iso: 'PN',
    name: 'Pitcairn',
    upperName: 'PITCAIRN',
    iso3: 'PCN',
    numCode: 612,
    phoneCode: 0,
  },
  {
    id: 171,
    iso: 'PL',
    name: 'Poland',
    upperName: 'POLAND',
    iso3: 'POL',
    numCode: 616,
    phoneCode: 48,
  },
  {
    id: 172,
    iso: 'PT',
    name: 'Portugal',
    upperName: 'PORTUGAL',
    iso3: 'PRT',
    numCode: 620,
    phoneCode: 351,
  },
  {
    id: 173,
    iso: 'PR',
    name: 'Puerto Rico',
    upperName: 'PUERTO RICO',
    iso3: 'PRI',
    numCode: 630,
    phoneCode: 1787,
  },
  {
    id: 174,
    iso: 'QA',
    name: 'Qatar',
    upperName: 'QATAR',
    iso3: 'QAT',
    numCode: 634,
    phoneCode: 974,
  },
  {
    id: 175,
    iso: 'RE',
    name: 'Reunion',
    upperName: 'REUNION',
    iso3: 'REU',
    numCode: 638,
    phoneCode: 262,
  },
  {
    id: 176,
    iso: 'RO',
    name: 'Romania',
    upperName: 'ROMANIA',
    iso3: 'ROU',
    numCode: 642,
    phoneCode: 40,
  },
  {
    id: 178,
    iso: 'RW',
    name: 'Rwanda',
    upperName: 'RWANDA',
    iso3: 'RWA',
    numCode: 646,
    phoneCode: 250,
  },
  {
    id: 179,
    iso: 'SH',
    name: 'Saint Helena',
    upperName: 'SAINT HELENA',
    iso3: 'SHN',
    numCode: 654,
    phoneCode: 290,
  },
  {
    id: 180,
    iso: 'KN',
    name: 'Saint Kitts and Nevis',
    upperName: 'SAINT KITTS AND NEVIS',
    iso3: 'KNA',
    numCode: 659,
    phoneCode: 1869,
  },
  {
    id: 181,
    iso: 'LC',
    name: 'Saint Lucia',
    upperName: 'SAINT LUCIA',
    iso3: 'LCA',
    numCode: 662,
    phoneCode: 1758,
  },
  {
    id: 182,
    iso: 'PM',
    name: 'Saint Pierre and Miquelon',
    upperName: 'SAINT PIERRE AND MIQUELON',
    iso3: 'SPM',
    numCode: 666,
    phoneCode: 508,
  },
  {
    id: 183,
    iso: 'VC',
    name: 'Saint Vincent and the Grenadines',
    upperName: 'SAINT VINCENT AND THE GRENADINES',
    iso3: 'VCT',
    numCode: 670,
    phoneCode: 1784,
  },
  {
    id: 184,
    iso: 'WS',
    name: 'Samoa',
    upperName: 'SAMOA',
    iso3: 'WSM',
    numCode: 882,
    phoneCode: 684,
  },
  {
    id: 185,
    iso: 'SM',
    name: 'San Marino',
    upperName: 'SAN MARINO',
    iso3: 'SMR',
    numCode: 674,
    phoneCode: 378,
  },
  {
    id: 186,
    iso: 'ST',
    name: 'Sao Tome and Principe',
    upperName: 'SAO TOME AND PRINCIPE',
    iso3: 'STP',
    numCode: 678,
    phoneCode: 239,
  },
  {
    id: 187,
    iso: 'SA',
    name: 'Saudi Arabia',
    upperName: 'SAUDI ARABIA',
    iso3: 'SAU',
    numCode: 682,
    phoneCode: 966,
  },
  {
    id: 188,
    iso: 'SN',
    name: 'Senegal',
    upperName: 'SENEGAL',
    iso3: 'SEN',
    numCode: 686,
    phoneCode: 221,
  },
  {
    id: 189,
    iso: 'RS',
    name: 'Serbia',
    upperName: 'SERBIA',
    iso3: 'SRB',
    numCode: 688,
    phoneCode: 381,
  },
  {
    id: 190,
    iso: 'SC',
    name: 'Seychelles',
    upperName: 'SEYCHELLES',
    iso3: 'SYC',
    numCode: 690,
    phoneCode: 248,
  },
  {
    id: 191,
    iso: 'SL',
    name: 'Sierra Leone',
    upperName: 'SIERRA LEONE',
    iso3: 'SLE',
    numCode: 694,
    phoneCode: 232,
  },
  {
    id: 192,
    iso: 'SG',
    name: 'Singapore',
    upperName: 'SINGAPORE',
    iso3: 'SGP',
    numCode: 702,
    phoneCode: 65,
  },
  {
    id: 193,
    iso: 'SK',
    name: 'Slovakia',
    upperName: 'SLOVAKIA',
    iso3: 'SVK',
    numCode: 703,
    phoneCode: 421,
  },
  {
    id: 194,
    iso: 'SI',
    name: 'Slovenia',
    upperName: 'SLOVENIA',
    iso3: 'SVN',
    numCode: 705,
    phoneCode: 386,
  },
  {
    id: 195,
    iso: 'SB',
    name: 'Solomon Islands',
    upperName: 'SOLOMON ISLANDS',
    iso3: 'SLB',
    numCode: 90,
    phoneCode: 677,
  },
  {
    id: 196,
    iso: 'SO',
    name: 'Somalia',
    upperName: 'SOMALIA',
    iso3: 'SOM',
    numCode: 706,
    phoneCode: 252,
  },
  {
    id: 197,
    iso: 'ZA',
    name: 'South Africa',
    upperName: 'SOUTH AFRICA',
    iso3: 'ZAF',
    numCode: 710,
    phoneCode: 27,
  },
  {
    id: 198,
    iso: 'GS',
    name: 'South Georgia and the South Sandwich Islands',
    upperName: 'SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS',
    iso3: 'SGS',
    numCode: 239,
    phoneCode: 0,
  },
  {
    id: 199,
    iso: 'ES',
    name: 'Spain',
    upperName: 'SPAIN',
    iso3: 'ESP',
    numCode: 724,
    phoneCode: 34,
  },
  {
    id: 200,
    iso: 'LK',
    name: 'Sri Lanka',
    upperName: 'SRI LANKA',
    iso3: 'LKA',
    numCode: 144,
    phoneCode: 94,
  },
  {
    id: 201,
    iso: 'SD',
    name: 'Sudan',
    upperName: 'SUDAN',
    iso3: 'SDN',
    numCode: 736,
    phoneCode: 249,
  },
  {
    id: 202,
    iso: 'SR',
    name: 'Suriname',
    upperName: 'SURINAME',
    iso3: 'SUR',
    numCode: 740,
    phoneCode: 597,
  },
  {
    id: 203,
    iso: 'SJ',
    name: 'Svalbard and Jan Mayen',
    upperName: 'SVALBARD AND JAN MAYEN',
    iso3: 'SJM',
    numCode: 744,
    phoneCode: 47,
  },
  {
    id: 204,
    iso: 'SZ',
    name: 'Swaziland',
    upperName: 'SWAZILAND',
    iso3: 'SWZ',
    numCode: 748,
    phoneCode: 268,
  },
  {
    id: 205,
    iso: 'SE',
    name: 'Sweden',
    upperName: 'SWEDEN',
    iso3: 'SWE',
    numCode: 752,
    phoneCode: 46,
  },
  {
    id: 206,
    iso: 'CH',
    name: 'Switzerland',
    upperName: 'SWITZERLAND',
    iso3: 'CHE',
    numCode: 756,
    phoneCode: 41,
  },
  {
    id: 207,
    iso: 'SY',
    name: 'Syrian Arab Republic',
    upperName: 'SYRIAN ARAB REPUBLIC',
    iso3: 'SYR',
    numCode: 760,
    phoneCode: 963,
  },
  {
    id: 208,
    iso: 'TW',
    name: 'Taiwan, Province of China',
    upperName: 'TAIWAN, PROVINCE OF CHINA',
    iso3: 'TWN',
    numCode: 158,
    phoneCode: 886,
  },
  {
    id: 209,
    iso: 'TJ',
    name: 'Tajikistan',
    upperName: 'TAJIKISTAN',
    iso3: 'TJK',
    numCode: 762,
    phoneCode: 992,
  },
  {
    id: 210,
    iso: 'TZ',
    name: 'Tanzania, United Republic of',
    upperName: 'TANZANIA, UNITED REPUBLIC OF',
    iso3: 'TZA',
    numCode: 834,
    phoneCode: 255,
  },
  {
    id: 211,
    iso: 'TH',
    name: 'Thailand',
    upperName: 'THAILAND',
    iso3: 'THA',
    numCode: 764,
    phoneCode: 66,
  },
  {
    id: 212,
    iso: 'TL',
    name: 'Timor-Leste',
    upperName: 'TIMOR-LESTE',
    iso3: 'TLS',
    numCode: 626,
    phoneCode: 670,
  },
  {
    id: 213,
    iso: 'TG',
    name: 'Togo',
    upperName: 'TOGO',
    iso3: 'TGO',
    numCode: 768,
    phoneCode: 228,
  },
  {
    id: 214,
    iso: 'TK',
    name: 'Tokelau',
    upperName: 'TOKELAU',
    iso3: 'TKL',
    numCode: 772,
    phoneCode: 690,
  },
  {
    id: 215,
    iso: 'TO',
    name: 'Tonga',
    upperName: 'TONGA',
    iso3: 'TON',
    numCode: 776,
    phoneCode: 676,
  },
  {
    id: 216,
    iso: 'TT',
    name: 'Trinidad and Tobago',
    upperName: 'TRINIDAD AND TOBAGO',
    iso3: 'TTO',
    numCode: 780,
    phoneCode: 1868,
  },
  {
    id: 217,
    iso: 'TN',
    name: 'Tunisia',
    upperName: 'TUNISIA',
    iso3: 'TUN',
    numCode: 788,
    phoneCode: 216,
  },
  {
    id: 218,
    iso: 'TR',
    name: 'Turkey',
    upperName: 'TURKEY',
    iso3: 'TUR',
    numCode: 792,
    phoneCode: 90,
  },
  {
    id: 219,
    iso: 'TM',
    name: 'Turkmenistan',
    upperName: 'TURKMENISTAN',
    iso3: 'TKM',
    numCode: 795,
    phoneCode: 993,
  },
  {
    id: 220,
    iso: 'TC',
    name: 'Turks and Caicos Islands',
    upperName: 'TURKS AND CAICOS ISLANDS',
    iso3: 'TCA',
    numCode: 796,
    phoneCode: 1649,
  },
  {
    id: 221,
    iso: 'TV',
    name: 'Tuvalu',
    upperName: 'TUVALU',
    iso3: 'TUV',
    numCode: 798,
    phoneCode: 688,
  },
  {
    id: 222,
    iso: 'UG',
    name: 'Uganda',
    upperName: 'UGANDA',
    iso3: 'UGA',
    numCode: 800,
    phoneCode: 256,
  },
  {
    id: 223,
    iso: 'UA',
    name: 'Ukraine',
    upperName: 'UKRAINE',
    iso3: 'UKR',
    numCode: 804,
    phoneCode: 380,
  },
  {
    id: 224,
    iso: 'AE',
    name: 'United Arab Emirates',
    upperName: 'UNITED ARAB EMIRATES',
    iso3: 'ARE',
    numCode: 784,
    phoneCode: 971,
  },
  {
    id: 225,
    iso: 'GB',
    name: 'United Kingdom',
    upperName: 'UNITED KINGDOM',
    iso3: 'GBR',
    numCode: 826,
    phoneCode: 44,
  },
  {
    id: 226,
    iso: 'US',
    name: 'United States',
    upperName: 'UNITED STATES',
    iso3: 'USA',
    numCode: 840,
    phoneCode: 1,
  },
  {
    id: 227,
    iso: 'UM',
    name: 'United States Minor Outlying Islands',
    upperName: 'UNITED STATES MINOR OUTLYING ISLANDS',
    iso3: 'UMI',
    numCode: 581,
    phoneCode: 1,
  },
  {
    id: 228,
    iso: 'UY',
    name: 'Uruguay',
    upperName: 'URUGUAY',
    iso3: 'URY',
    numCode: 858,
    phoneCode: 598,
  },
  {
    id: 229,
    iso: 'UZ',
    name: 'Uzbekistan',
    upperName: 'UZBEKISTAN',
    iso3: 'UZB',
    numCode: 860,
    phoneCode: 998,
  },
  {
    id: 230,
    iso: 'VU',
    name: 'Vanuatu',
    upperName: 'VANUATU',
    iso3: 'VUT',
    numCode: 548,
    phoneCode: 678,
  },
  {
    id: 231,
    iso: 'VE',
    name: 'Venezuela',
    upperName: 'VENEZUELA',
    iso3: 'VEN',
    numCode: 862,
    phoneCode: 58,
  },
  {
    id: 232,
    iso: 'VN',
    name: 'Viet Nam',
    upperName: 'VIET NAM',
    iso3: 'VNM',
    numCode: 704,
    phoneCode: 84,
  },
  {
    id: 233,
    iso: 'VG',
    name: 'Virgin Islands, British',
    upperName: 'VIRGIN ISLANDS, BRITISH',
    iso3: 'VGB',
    numCode: 92,
    phoneCode: 1284,
  },
  {
    id: 234,
    iso: 'VI',
    name: 'Virgin Islands, U.s.',
    upperName: 'VIRGIN ISLANDS, U.S.',
    iso3: 'VIR',
    numCode: 850,
    phoneCode: 1340,
  },
  {
    id: 235,
    iso: 'WF',
    name: 'Wallis and Futuna',
    upperName: 'WALLIS AND FUTUNA',
    iso3: 'WLF',
    numCode: 876,
    phoneCode: 681,
  },
  {
    id: 236,
    iso: 'EH',
    name: 'Western Sahara',
    upperName: 'WESTERN SAHARA',
    iso3: 'ESH',
    numCode: 732,
    phoneCode: 212,
  },
  {
    id: 237,
    iso: 'YE',
    name: 'Yemen',
    upperName: 'YEMEN',
    iso3: 'YEM',
    numCode: 887,
    phoneCode: 967,
  },
  {
    id: 238,
    iso: 'ZM',
    name: 'Zambia',
    upperName: 'ZAMBIA',
    iso3: 'ZMB',
    numCode: 894,
    phoneCode: 260,
  },
  {
    id: 239,
    iso: 'ZW',
    name: 'Zimbabwe',
    upperName: 'ZIMBABWE',
    iso3: 'ZWE',
    numCode: 716,
    phoneCode: 263,
  },
  {
    id: 240,
    iso: 'ME',
    name: 'Montenegro',
    upperName: 'MONTENEGRO',
    iso3: 'MNE',
    numCode: 499,
    phoneCode: 382,
  },
  {
    id: 241,
    iso: 'XK',
    name: 'Kosovo',
    upperName: 'KOSOVO',
    iso3: 'XKX',
    numCode: 0,
    phoneCode: 383,
  },
  {
    id: 242,
    iso: 'AX',
    name: 'Aland Islands',
    upperName: 'ALAND ISLANDS',
    iso3: 'ALA',
    numCode: 248,
    phoneCode: 358,
  },
  {
    id: 243,
    iso: 'BQ',
    name: 'Bonaire, Sint Eustatius and Saba',
    upperName: 'BONAIRE, SINT EUSTATIUS AND SABA',
    iso3: 'BES',
    numCode: 535,
    phoneCode: 599,
  },
  {
    id: 244,
    iso: 'CW',
    name: 'Curacao',
    upperName: 'CURACAO',
    iso3: 'CUW',
    numCode: 531,
    phoneCode: 599,
  },
  {
    id: 245,
    iso: 'GG',
    name: 'Guernsey',
    upperName: 'GUERNSEY',
    iso3: 'GGY',
    numCode: 831,
    phoneCode: 44,
  },
  {
    id: 246,
    iso: 'IM',
    name: 'Isle of Man',
    upperName: 'ISLE OF MAN',
    iso3: 'IMN',
    numCode: 833,
    phoneCode: 44,
  },
  {
    id: 247,
    iso: 'JE',
    name: 'Jersey',
    upperName: 'JERSEY',
    iso3: 'JEY',
    numCode: 832,
    phoneCode: 44,
  },
  {
    id: 248,
    iso: 'BL',
    name: 'Saint Barthelemy',
    upperName: 'SAINT BARTHELEMY',
    iso3: 'BLM',
    numCode: 652,
    phoneCode: 590,
  },
  {
    id: 249,
    iso: 'MF',
    name: 'Saint Martin',
    upperName: 'SAINT MARTIN',
    iso3: 'MAF',
    numCode: 663,
    phoneCode: 590,
  },
  {
    id: 250,
    iso: 'SX',
    name: 'Sint Maarten',
    upperName: 'SINT MAARTEN',
    iso3: 'SXM',
    numCode: 534,
    phoneCode: 1,
  },
  {
    id: 251,
    iso: 'SS',
    name: 'South Sudan',
    upperName: 'SOUTH SUDAN',
    iso3: 'SSD',
    numCode: 728,
    phoneCode: 211,
  },
];
